title: Paul Rübsamen-v. Döhren
description: This is a Website about me, Paul RvD

# Language
lang: en 
languages: ["en", "norsk", "de"] 
permalink: /:categories/:year/:month/:day/:title/

collections:
    publications:
        output: true
    recepies:
    freetime:


# Where things are
source              : .
destination         : ./_site
plugins_dir         : _plugins # takes an array of strings and loads plugins in that order
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes


theme: bulma-clean-theme

# Handling Reading
safe                : false
include             : [".htaccess"]
exclude             : ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files          : [".git", ".svn"]
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

#paginate
paginate: 5
paginate_path: "/blog/page:num/"

# Header Option
#header: large

# Conversion
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false


liquid:
  error_mode        : warn
  strict_filters    : false
  strict_variables  : false


kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : [1, 2, 3, 4, 5, 6]
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false


social:
  instagram: friesischereber 
  facebook: paul.rubsamenvdohren
  linkedin: paul-rübsamen-v-döhren-5389731b6
  rgate: Paul-Ruebsamen-Von-Doehren
  github: FriesischerEber
  twitch: frieber
  email: paulrvd@proton.me

disqus:
    shortname: FRIEBER
